version: "3"

services:
  mysql:
    image: "mysql:5.6"
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "db"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  postgres:
    image: "postgres:11-alpine"
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db